# Generated by Django 4.2 on 2023-04-08 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_category_color_image_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
    ]
