# Generated by Django 4.2 on 2023-04-09 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_version',
            name='size',
        ),
    ]
