# Generated by Django 4.2 on 2023-04-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_product_version_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_version',
            name='size',
            field=models.ManyToManyField(blank=True, to='product.size'),
        ),
    ]
