# Generated by Django 4.2 on 2023-04-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_version_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_version',
            name='date',
        ),
        migrations.AddField(
            model_name='product_version',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
