# Generated by Django 4.2 on 2023-04-09 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_remove_product_version_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_version',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
