# Generated by Django 4.2 on 2023-04-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_product_version_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_version',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
