# Generated by Django 4.2 on 2023-07-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_product_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_version',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The discounted price of the product', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product_version',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='The regular price of the product', max_digits=8, null=True),
        ),
    ]
