# Generated by Django 4.2 on 2023-07-20 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_product_version_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_version',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='product_version',
            name='price',
        ),
    ]
