# Generated by Django 4.2 on 2023-07-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_remove_product_discount_price_remove_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_version',
            name='storage',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
