# Generated by Django 4.2 on 2023-07-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_product_version_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='product_version',
            name='storage',
        ),
        migrations.AddField(
            model_name='product_version',
            name='storage',
            field=models.ManyToManyField(blank=True, to='product.storage'),
        ),
    ]
