# Generated by Django 4.2 on 2023-07-20 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_storage_remove_product_version_storage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_version',
            name='storage',
        ),
        migrations.AddField(
            model_name='product_version',
            name='storage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='product_storage', to='product.storage'),
            preserve_default=False,
        ),
    ]
