# Generated by Django 4.2 on 2023-07-20 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_alter_product_version_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_version',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_storage', to='product.storage'),
        ),
    ]
