# Generated by Django 4.2 on 2023-08-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_alter_product_version_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_version',
            name='in_basket',
            field=models.BooleanField(default=False, help_text='Check if the product is basket'),
        ),
        migrations.AddField(
            model_name='product_version',
            name='in_wishlist',
            field=models.BooleanField(default=False, help_text='Check if the product is in wishlist'),
        ),
    ]
